In [21]:
import numpy as np

# C = np.arange(15, dtype=np.int64).reshape(3,5)
A = np.zeros((3,5), dtype=np.int64)
B = np.arange(3, dtype=np.int64).reshape(3,1)

print(A)
print('--------------')
print(B)
print('-------------')
print(A+B)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
--------------
[[0]
 [1]
 [2]]
-------------
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
