In [2]:
import torch

In [7]:
# empty 5x3 matrix
x = torch.empty(5, 3)
print(x, type(x))

tensor([[ 0.0000e+00, -4.6566e-10, -6.9914e+19],
        [-1.5849e+29,  2.8889e-33,  1.4013e-45],
        [ 2.3919e-33,  1.4013e-45,  2.3919e-33],
        [ 1.4013e-45,  2.6708e-33,  1.4013e-45],
        [ 2.7011e-33,  1.4013e-45,  2.6711e-33]]) <class 'torch.Tensor'>


In [8]:
# randomly initialized 5x3 matrix
x = torch.rand(5, 3)
print(x, type(x))

tensor([[0.0964, 0.7070, 0.2229],
        [0.0456, 0.4247, 0.6808],
        [0.9165, 0.5527, 0.8074],
        [0.8114, 0.0189, 0.4145],
        [0.5576, 0.5429, 0.9911]]) <class 'torch.Tensor'>


In [12]:
# 5x3 matrix filled with 0 and dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x, type(x), x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) <class 'torch.Tensor'> torch.int64


In [15]:
# construct tensor directly from data
x = torch.tensor([5.5, 3])
print(x, type(x), x.dtype)

tensor([5.5000, 3.0000]) <class 'torch.Tensor'> torch.float32


In [20]:
# create tensor based on existing one
x = x.new_ones(5, 3, dtype=torch.double)
print(x, x.dtype, id(x))

x = torch.rand_like(x, dtype=torch.float)
print(x, x.dtype, id(x))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.float64 4533417736
tensor([[0.0294, 0.1715, 0.9970],
        [0.1221, 0.9346, 0.8208],
        [0.5304, 0.6602, 0.0134],
        [0.3364, 0.3874, 0.0096],
        [0.6085, 0.1711, 0.8859]]) torch.float32 4483065824


In [25]:
# get tensor's size
# type torch.Size == tuple
print(x.size(), type(x.size()), list(x.size()))

torch.Size([5, 3]) <class 'torch.Size'> [5, 3]


In [43]:
# matrix addition
y = torch.rand(5,3)
print('x:', x)
print('y:', y)
print('x+y:', x + y)
print('--------------------------------------')

print('torch.add(x, y):', torch.add(x, y))
print('--------------------------------------')

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

print('--------------------------------------')
print('y.add(x):', y.add(x))
print('y:', y)

x: tensor([[0.0294, 0.1715, 0.9970],
        [0.1221, 0.9346, 0.8208],
        [0.5304, 0.6602, 0.0134],
        [0.3364, 0.3874, 0.0096],
        [0.6085, 0.1711, 0.8859]])
y: tensor([[0.3232, 0.2194, 0.5416],
        [0.7129, 0.1288, 0.6510],
        [0.7905, 0.9972, 0.5840],
        [0.7286, 0.0869, 0.8749],
        [0.1476, 0.7802, 0.7019]])
x+y: tensor([[0.3526, 0.3909, 1.5386],
        [0.8350, 1.0635, 1.4717],
        [1.3209, 1.6574, 0.5974],
        [1.0650, 0.4743, 0.8845],
        [0.7561, 0.9513, 1.5878]])
--------------------------------------
torch.add(x, y): tensor([[0.3526, 0.3909, 1.5386],
        [0.8350, 1.0635, 1.4717],
        [1.3209, 1.6574, 0.5974],
        [1.0650, 0.4743, 0.8845],
        [0.7561, 0.9513, 1.5878]])
--------------------------------------
tensor([[0.3526, 0.3909, 1.5386],
        [0.8350, 1.0635, 1.4717],
        [1.3209, 1.6574, 0.5974],
        [1.0650, 0.4743, 0.8845],
        [0.7561, 0.9513, 1.5878]])
--------------------------------------


In [44]:
# in-place addition
# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
y.add_(x)
print('x:', x)
print('y:', y)

x: tensor([[0.0294, 0.1715, 0.9970],
        [0.1221, 0.9346, 0.8208],
        [0.5304, 0.6602, 0.0134],
        [0.3364, 0.3874, 0.0096],
        [0.6085, 0.1711, 0.8859]])
y: tensor([[0.3526, 0.3909, 1.5386],
        [0.8350, 1.0635, 1.4717],
        [1.3209, 1.6574, 0.5974],
        [1.0650, 0.4743, 0.8845],
        [0.7561, 0.9513, 1.5878]])


In [46]:
# numpy like indexing
print('x[:, 1]:', x[:, 1])

x[:, 1]: tensor([0.1715, 0.9346, 0.6602, 0.3874, 0.1711])


In [52]:
# resizing matrix
x = torch.randn(4, 4)
print('x:', x)
y = x.view(16)
print('y:', y)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print('z:', z)
print(x.size(), y.size(), z.size())

x: tensor([[ 0.7162,  0.5314, -0.6820, -0.6752],
        [ 0.6262, -0.6024, -1.1568,  1.9076],
        [-0.6742,  0.5660,  0.1276, -1.4177],
        [ 0.6172, -2.5691,  0.4735,  0.6304]])
y: tensor([ 0.7162,  0.5314, -0.6820, -0.6752,  0.6262, -0.6024, -1.1568,  1.9076,
        -0.6742,  0.5660,  0.1276, -1.4177,  0.6172, -2.5691,  0.4735,  0.6304])
z: tensor([[ 0.7162,  0.5314, -0.6820, -0.6752,  0.6262, -0.6024, -1.1568,  1.9076],
        [-0.6742,  0.5660,  0.1276, -1.4177,  0.6172, -2.5691,  0.4735,  0.6304]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [54]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x, x.item())

tensor([-1.4985]) -1.4984947443008423


In [61]:
# Converting a Torch Tensor to a NumPy Array
# .numpy() 이용할 경우, torch tensor와 numpy ndarray가 같은 값을 공유
a = torch.ones(5)
print(a)
b = a.numpy()
print(b, type(b), b.dtype)
print('-------------------')

a.add_(1)
print(a)
print(b)
print(id(a), id(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'> float32
-------------------
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
4681972760 4681967936


In [63]:
# See how changing the np array changed the Torch Tensor automatically
# torch.from_numpy()를 이용할 경우, torch tensor와 numpy ndarray가 같은 값을 공유
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [68]:
# Tensors can be moved onto any device using the .to method.
print(torch.cuda.is_available())

False
